/*

 Author: Oguz Gelal

 Backcheck is an algorithm that takes an URL, trims every possible extension
 and simplifies it as much as possible. It takes out http, www and and other
 arguments which is not responsible for navigation. This is to make sure users
 on the same page could join the same room generated by the URL.

 For example, think of a site that keeps record of navigation referances. Every
 link to a page contains an argument "ref" which provides information (of where
 the users on that page came from) to the backend. This will cause two users
 viewing the same page but has navigated there from different pages to have
 two different URL's.

*/

Meteor.methods({

	backcheck: function(url){
		console.log(Meteor);
		var req = HTTP.get(url, function(){
			console.log(req);
		});
	}

});
