/*
Author: Oguz Gelal

FUTURE

Backcheck is an algorithm that takes an URL, trims every possible extension
and simplifies it as much as possible. It takes out http, www and and other
arguments which is not responsible for navigation. This is to make sure users
on the same page could join the same room generated by the URL.

For example, think of a site that keeps record of navigation referances. Every
link to a page contains an argument "ref" which provides information (of where
the users on that page came from) to the backend. This will cause two users
viewing the same page but has navigated there from different pages to have
two different URL's.

FOR NOW

For now, after getting rid of 'http(s)://www.' part, the algorithm will simply
ignore anything after an hashtag. This will eliminate anchor links. It will
also ignore some keywords such as 'ref' 'referance'.

*/

/*
;(function() {

	var ignoreArgs = ["ref", "referance"];
	var backcheck = function(url) {
		console.log("backcheck working...");
		console.log(url);
		return "done";
	}

})();
*/




